/**
 * Códigos de erro padronizados para fácil referência
 */
export const ERROR_CODES = {
	// Moodle
	MOODLE_ERROR: 'MOODLE_ERROR',
	MOODLE_AUTH_ERROR: 'MOODLE_AUTH_ERROR',
	MOODLE_CONNECTION_ERROR: 'MOODLE_CONNECTION_ERROR',
	MOODLE_INVALID_PARAMETERS: 'MOODLE_INVALID_PARAMETERS',
	MOODLE_INVALID_RESPONSE: 'MOODLE_INVALID_RESPONSE',
	MOODLE_RATE_LIMIT: 'MOODLE_RATE_LIMIT',
	MOODLE_RESOURCE_NOT_FOUND: 'MOODLE_RESOURCE_NOT_FOUND',
	MOODLE_TIMEOUT_ERROR: 'MOODLE_TIMEOUT_ERROR',

	// Webhook
	WEBHOOK_ERROR: 'WEBHOOK_ERROR',
	WEBHOOK_DUPLICATE_ERROR: 'WEBHOOK_DUPLICATE_ERROR',
	WEBHOOK_EVENT_PROCESSING_ERROR: 'WEBHOOK_EVENT_PROCESSING_ERROR',
	WEBHOOK_INVALID_FORMAT: 'WEBHOOK_INVALID_FORMAT',
	WEBHOOK_INVALID_TOKEN: 'WEBHOOK_INVALID_TOKEN',
	WEBHOOK_PAYLOAD_TOO_LARGE: 'WEBHOOK_PAYLOAD_TOO_LARGE',
	WEBHOOK_RATE_LIMIT: 'WEBHOOK_RATE_LIMIT',
	WEBHOOK_TIMEOUT_ERROR: 'WEBHOOK_TIMEOUT_ERROR',
	WEBHOOK_UNSUPPORTED_EVENT: 'WEBHOOK_UNSUPPORTED_EVENT',

	// Queue
	QUEUE_ERROR: 'QUEUE_ERROR',
	QUEUE_CAPACITY_EXCEEDED: 'QUEUE_CAPACITY_EXCEEDED',
	QUEUE_CONNECTION_ERROR: 'QUEUE_CONNECTION_ERROR',
	QUEUE_CONSUME_ERROR: 'QUEUE_CONSUME_ERROR',
	QUEUE_CREATION_ERROR: 'QUEUE_CREATION_ERROR',
	QUEUE_INVALID_MESSAGE: 'QUEUE_INVALID_MESSAGE',
	QUEUE_NOT_FOUND: 'QUEUE_NOT_FOUND',
	QUEUE_PUBLISH_ERROR: 'QUEUE_PUBLISH_ERROR',
	QUEUE_TIMEOUT_ERROR: 'QUEUE_TIMEOUT_ERROR',

	// System
	CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
	DNS_ERROR: 'DNS_ERROR',
	INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
	INVALID_DATA_FORMAT: 'INVALID_DATA_FORMAT',
	MISSING_CONFIGURATION: 'MISSING_CONFIGURATION',
	MISSING_DATA: 'MISSING_DATA',
	NETWORK_ERROR: 'NETWORK_ERROR',
	NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
	VALIDATION_ERROR: 'VALIDATION_ERROR',

	// Event
	EVENT_ERROR: 'EVENT_ERROR',
	EVENT_HANDLER_EXECUTION_ERROR: 'EVENT_HANDLER_EXECUTION_ERROR',
	EVENT_HANDLER_NOT_FOUND: 'EVENT_HANDLER_NOT_FOUND',
	EVENT_HANDLER_TIMEOUT: 'EVENT_HANDLER_TIMEOUT',
	EVENT_INVALID_FORMAT: 'EVENT_INVALID_FORMAT',
	EVENT_REJECTED: 'EVENT_REJECTED',
	EVENT_SERIALIZATION_ERROR: 'EVENT_SERIALIZATION_ERROR',
	EVENT_VERSION_NOT_SUPPORTED: 'EVENT_VERSION_NOT_SUPPORTED',
} as const;
